### ISSUE TITLE
Click box rotation bug

### ISSUE THREAD

**Issue by zxybazh** [y-x-c/todos#1]
When doing check the completed list I noticed a rotated check box before what needs to be done

**Comment by Orthocenter** [comment]
What browser did you use? And what device?

**Comment by zxybazh** [comment]
Ubuntu 14.04 x86_64 Firefox 38.0 After type task2 atfer task1 then tick the box before task2 and I can see a rotated check box in todos/completed before "What needs to be done"

**Comment by Orthocenter** [comment]
Since I used some CSS features supported only by webkit kernel, so currently only desktop version of chrome/safari is fully supported. I will improve compatibility as soon as possible.
